apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-http-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-http-server
  template:
    metadata:
      labels:
        app: nodejs-http-server
    spec:
      containers:
        - name: nodejs-http-server
          image: hi1280/nodejs-http-server:0.0.1
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-http-server
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: nodejs-http-server